# Gerado a partir do enum ggml_op em ggml/include/ggml.h (llama.cpp b10010).
# O indice na lista = valor do enum = campo `op` lido do ggml_tensor pelo eBPF.
GGML_OPS = [
    "NONE", "DUP", "ADD", "ADD_ID", "ADD1", "ACC",
    "SUB", "MUL", "DIV", "SQR", "SQRT", "LOG",
    "SIN", "COS", "SUM", "SUM_ROWS", "CUMSUM", "MEAN",
    "ARGMAX", "COUNT_EQUAL", "REPEAT", "REPEAT_BACK", "CONCAT", "SILU_BACK",
    "NORM", "RMS_NORM", "RMS_NORM_BACK", "GROUP_NORM", "L2_NORM", "MUL_MAT",
    "MUL_MAT_ID", "OUT_PROD", "SCALE", "SET", "CPY", "CONT",
    "RESHAPE", "VIEW", "PERMUTE", "TRANSPOSE", "GET_ROWS", "GET_ROWS_BACK",
    "SET_ROWS", "DIAG", "DIAG_MASK_INF", "DIAG_MASK_ZERO", "SOFT_MAX", "SOFT_MAX_BACK",
    "ROPE", "ROPE_BACK", "CLAMP", "CONV_TRANSPOSE_1D", "IM2COL", "IM2COL_BACK",
    "IM2COL_3D", "COL2IM_1D", "CONV_2D", "CONV_3D", "CONV_2D_DW", "CONV_TRANSPOSE_2D",
    "POOL_1D", "POOL_2D", "POOL_2D_BACK", "UPSCALE", "PAD", "PAD_REFLECT_1D",
    "ROLL", "ARANGE", "TIMESTEP_EMBEDDING", "ARGSORT", "TOP_K", "LEAKY_RELU",
    "TRI", "FILL", "FLASH_ATTN_EXT", "FLASH_ATTN_BACK", "SSM_CONV", "SSM_SCAN",
    "WIN_PART", "WIN_UNPART", "GET_REL_POS", "ADD_REL_POS", "RWKV_WKV6", "GATED_LINEAR_ATTN",
    "RWKV_WKV7", "SOLVE_TRI", "GATED_DELTA_NET", "LIGHTNING_INDEXER", "UNARY", "MAP_CUSTOM1",
    "MAP_CUSTOM2", "MAP_CUSTOM3", "CUSTOM", "CROSS_ENTROPY_LOSS", "CROSS_ENTROPY_LOSS_BACK", "OPT_STEP_ADAMW",
    "OPT_STEP_SGD", "GLU",
]
